# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
#tasks:
#  - name: Script Task
#    init: echo 'init script' # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
#    command: echo 'start script'

tasks:
   - name: AWS-CLI
     env: 
      AWS_CLI_AUTO_PROMPT: on-partial
     before: 
      cd /workspace
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip awscliv2.zip
      sudo ./aws/install
      cd $THEIA_WORKSPACE_ROOT

# export AWS_ACCESS_KEY_ID=
# export AWS_SECRET_ACCESS_KEY=
# export AWS_DEFAULT_REGION=us-east-1
# gp env AWS_ACCESS_KEY_ID=
# gp env AWS_SECRET_ACCESS_KEY=
# gp env AWS_DEFAULT_REGION=us-east-1


# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
#ports:
#  - name: Frontend
#    description: Port 3000 for the frontend
#    port: 3000
#    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

