AWSTemplateFormatVersion: 2010-09-09
Description: Create A Role for us assume and create a resource we'll have to access
Parameters:
  BucketName:
    Type: String
    Default: "sts-fun-ab-65535"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
  STSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - s3.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
  RolePolicies:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: s3access
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: "*"
          Resource:
            - !Sub "arn:aws:s3:::${BucketName}"
            - !Sub "arn:aws:s3:::${BucketName}/*"
          
      Roles:
      - !Ref STSRole

